// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdrntenfuyvwtbtlephx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkcm50ZW5mdXl2d3RidGxlcGh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NTQ5MTIsImV4cCI6MjA2NzUzMDkxMn0.3P3X_FevkKy3n-heNHqHco3SkJfDKm5Eidoxw0CBmmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});